# Generated by Django 5.0.2 on 2024-03-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSalud', '0002_remove_paciente_asegurado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('pediatria', 'Pediatría'), ('cardiologia', 'Cardiología'), ('neurologia', 'Neurología'), ('psicologia', 'Psicología'), ('traumatologia', 'Traumatología'), ('oncologia', 'Oncología'), ('otros', 'Otros')], max_length=30),
        ),
    ]
